name = "Mindful Optimized 1.19.4"
author = "Lautner"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d85ba01da758c26deaf582b248ebfc9eb64b6a241ea9b6d707fb59fc194ddcca"

[versions]
minecraft = "1.19.4"
quilt = "0.18.6"
