name = "Mindful Optimized"
author = "Lautner"
version = "6.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c0fd7468f11ad5fef930b03e093b909362f348f32717a2cea19fd15759fd2a1a"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.13"
