name = "Mindful Optimized 1.19.4 v6.0.0"
author = "Lautner"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52bb598548ebeaeefc5e3e8016d2a81d843a7fb5e4e8bc9474622cd3b1ed2ea8"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
