name = "Mindful Optimized"
author = "Lautner"
version = "6.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c0ce63f50861a929a4e73a9bb1e18dd8b2a5d35f5206cc49fd5ba3e66a60135"

[versions]
minecraft = "1.19.4"
quilt = "0.19.0-beta.13"
