name = "Mindful Optimized 1.19.4"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2995beca69107a56b5abaa85f67cf73b677c8e32498327e39eba8540f924201e"

[versions]
fabric = "0.14.16"
minecraft = "1.19.4"
